### ISSUE TITLE
no texture on drogue chute when deployed 

### ISSUE THREAD

**Issue by nolifejordan** [TundraMods/TundraExploration#103]
![image](https://github.com/TundraMods/TundraExploration/assets/80071688/aae934ca-46e9-4b2e-a890-2b61dcfc8da7)
![image](https://github.com/TundraMods/TundraExploration/assets/80071688/3170ac63-829a-45d9-a79b-b60b93581304)
the main chute works normal

**Comment by TundraMods** [comment]
What KSP version is this? Any other visual mods installed? Did you completely remove the old TE version before installing the new one?

**Comment by nolifejordan** [comment]
KSP 1.12.5
i deleted TE before installing
and full list of mods 
![Screenshot 2023-11-05 235155](https://github.com/TundraMods/TundraExploration/assets/80071688/0e63075e-e643-4802-bf87-6a32d7864516)
![Screenshot 2023-11-05 235123](https://github.com/TundraMods/TundraExploration/assets/80071688/18d24532-69f8-4017-92db-cd83db6beb6e)

**Comment by TundraMods** [comment]
Looks like you have the Depthmask mod installed. I haven't tried using my version of the depthmask mod with that one. I will do some tests to make sure. Can you send me your log as well?

**Comment by nolifejordan** [comment]
[KSP.zip](https://github.com/TundraMods/TundraExploration/files/13264215/KSP.zip)
log file too large so i zipped it

**Comment by TundraMods** [comment]
Fixed the issue!

https://github.com/TundraMods/TundraExploration/commit/b22fef71fbef9f9fec5a08e005bc80cb2a660c13
