### ISSUE TITLE
WHAT DOWNLOAD FOR 1.12.4? THEY DONT SAY

### ISSUE THREAD

**Issue by ATOMPEAR** [TundraMods/TundraExploration#111]

**Comment by towermom9** [comment]
use ckan?

**Comment by SofieBrink** [comment]
Just the latest works fine

**Comment by ATOMPEAR** [comment]
YES Ive found out that for the most part just using the latest works. At least with the difference between .4 and.5 seems to be so little it has no effect. Maybe jumping 11.5 to 12.5 there would be an issue. Thaks for you responses though guys :)
